[tool.poetry]
name = "momento-wire-types"
version = "0.0.0"
description = "Momento Client Proto Generated Files"
authors = ["Momento <hello@momentohq.com>"]

license = "Apache-2.0"

documentation = "https://docs.momentohq.com/"
homepage = "https://gomomento.com"
readme = "README.md"
repository = "https://github.com/momentohq/client-protos"

keywords = ["Momento", "caching", "key-value store", "serverless"]

classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Operating System :: OS Independent",
  "Framework :: AsyncIO",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Topic :: Internet",
  "Natural Language :: English",
  "Typing :: Typed",
]

include = ["momento_wire_types/**/*.py", "momento_wire_types/**/*.pyi"]

[tool.poetry.dependencies]
python = "^3.7"
protobuf = ">=3,<5"
grpcio = "*"


[tool.poetry.group.dev.dependencies]
grpcio-tools = "^1.54.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
